"""remove_location

Revision ID: 50652a0b5a28
Revises: 8ddd1e13d03f
Create Date: 2024-08-14 14:56:29.186612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50652a0b5a28'
down_revision: Union[str, None] = '8ddd1e13d03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('blogs', 'body',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('blogs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_information', 'name',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('user_information', 'email',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('user_information', 'password',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('user_information', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_information', sa.Column('location', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('user_information', 'password',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('user_information', 'email',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('user_information', 'name',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('blogs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blogs', 'body',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
