"""add_description

Revision ID: e4fb234ac7ef
Revises: 50652a0b5a28
Create Date: 2024-08-16 10:35:33.843161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4fb234ac7ef'
down_revision: Union[str, None] = '50652a0b5a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_information', sa.Column('description', sa.String(length=500), nullable=False,  server_default="Avi"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_information', 'description')
    # ### end Alembic commands ###
